import { ArrowDown, ArrowUp, ImagePlus, LoaderCircle, RefreshCw, Star, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import axiosClient from "../../api/axiosClient";
const MAX_BYTES=5*1024*1024, allowed=new Set(["image/jpeg","image/png","image/webp"]);
export default function ProductImageManager({productId}){const [images,setImages]=useState([]),[version,setVersion]=useState(0),[pending,setPending]=useState([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(""),[deleting,setDeleting]=useState(null);const inputRef=useRef(null);
const load=useCallback(async()=>{try{const{data}=await axiosClient.get(`/products/${productId}/images`,{sessionProtected:true});setImages(data.data.images);setVersion(data.data.version);setError("")}catch(e){setError(e.response?.data?.message||"Không thể tải hình ảnh sản phẩm.")}},[productId]);useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer)},[load]);useEffect(()=>()=>pending.forEach(i=>URL.revokeObjectURL(i.preview)),[pending]);
const choose=e=>{const files=[...(e.target.files||[])];setError("");if(files.some(f=>!allowed.has(f.type)))return setError("Chỉ hỗ trợ JPEG, PNG và WebP.");if(files.some(f=>f.size>MAX_BYTES))return setError("Mỗi ảnh không được vượt quá 5 MB.");if(files.length>6)return setError("Mỗi lần chỉ được chọn tối đa 6 ảnh.");setPending(files.map(file=>({file,preview:URL.createObjectURL(file)})))};
const upload=async()=>{if(!pending.length||busy)return;setBusy(true);setProgress(0);setError("");const form=new FormData();pending.forEach(({file})=>form.append("images",file));form.append("expectedVersion",String(version));try{const{data}=await axiosClient.post(`/products/${productId}/images`,form,{sessionProtected:true,onUploadProgress:e=>setProgress(e.total?Math.round(e.loaded*100/e.total):0)});setImages(data.data.images);setVersion(data.data.version);setPending([])}catch(e){setError(e.response?.data?.message||"Không thể tải ảnh lên.");if(e.response?.status===409)await load()}finally{setBusy(false)}};
const reorder=async(next,primary=next[0]?.imageKey)=>{if(busy)return;setBusy(true);setError("");try{const{data}=await axiosClient.patch(`/products/${productId}/images/order`,{imageKeys:next.map(i=>i.imageKey),primaryImageKey:primary,expectedVersion:version},{sessionProtected:true});setImages(data.data.images);setVersion(data.data.version)}catch(e){setError(e.response?.data?.message||"Không thể sắp xếp ảnh.");if(e.response?.status===409)await load()}finally{setBusy(false)}};
const move=(index,offset)=>{const next=[...images],target=index+offset;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];reorder(next)};
const remove=async()=>{if(!deleting||busy)return;setBusy(true);try{const{data}=await axiosClient.delete(`/products/${productId}/images/${encodeURIComponent(deleting.imageKey)}`,{sessionProtected:true,data:{expectedVersion:version}});setImages(data.data.images);setVersion(data.data.version);setDeleting(null)}catch(e){setError(e.response?.data?.message||"Không thể xóa ảnh.");if(e.response?.status===409)await load()}finally{setBusy(false)}};
const replace=async(image,file)=>{if(!file||busy)return;if(!allowed.has(file.type)||file.size>MAX_BYTES)return setError("Ảnh thay thế phải là JPEG, PNG hoặc WebP và không quá 5 MB.");setBusy(true);const form=new FormData();form.append("image",file);form.append("expectedVersion",String(version));try{const{data}=await axiosClient.put(`/products/${productId}/images/${encodeURIComponent(image.imageKey)}`,form,{sessionProtected:true});setImages(data.data.images);setVersion(data.data.version)}catch(e){setError(e.response?.data?.message||"Không thể thay ảnh.");if(e.response?.status===409)await load()}finally{setBusy(false)}};
return <section className="form-card product-images-manager"><div className="image-manager-heading"><div><h3>Hình ảnh sản phẩm</h3><p>Ảnh đầu tiên là ảnh đại diện. Tối đa 10 ảnh.</p></div><button type="button" className="btn btn-light" disabled={busy} onClick={()=>inputRef.current?.click()}><ImagePlus/> Chọn ảnh</button></div><input ref={inputRef} hidden multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={choose}/>{error&&<div className="form-error" role="alert">{error} <button type="button" onClick={load}><RefreshCw/> Tải lại</button></div>}{pending.length>0&&<div className="image-pending"><div className="product-image-grid">{pending.map(i=><img key={i.preview} src={i.preview} alt="Ảnh chờ tải lên"/>)}</div><div className="image-upload-actions"><button type="button" className="btn btn-dark" disabled={busy} onClick={upload}>{busy?<><LoaderCircle className="spin"/> Đang tải {progress}%</>:"Tải ảnh lên"}</button><button type="button" className="btn btn-light" disabled={busy} onClick={()=>setPending([])}><X/> Bỏ chọn</button></div></div>}<div className="product-image-grid">{images.map((image,index)=><article key={image.imageKey}><img src={image.url} alt={`Ảnh sản phẩm ${index+1}`}/>{image.isPrimary&&<span><Star/> Ảnh đại diện</span>}{!image.managed&&<small>Ảnh cũ</small>}<div><button type="button" disabled={busy||index===0} onClick={()=>move(index,-1)} aria-label="Đưa ảnh lên"><ArrowUp/></button><button type="button" disabled={busy||index===images.length-1} onClick={()=>move(index,1)} aria-label="Đưa ảnh xuống"><ArrowDown/></button>{!image.isPrimary&&<button type="button" disabled={busy} onClick={()=>reorder(images,image.imageKey)} aria-label="Đặt làm ảnh đại diện"><Star/></button>}<label aria-label="Thay ảnh"><RefreshCw/><input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>replace(image,e.target.files?.[0])}/></label><button type="button" disabled={busy} onClick={()=>setDeleting(image)} aria-label="Xóa ảnh"><Trash2/></button></div></article>)}</div>{!images.length&&!pending.length&&<p className="image-empty">Sản phẩm chưa có hình ảnh.</p>}{deleting&&<div className="confirm-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDeleting(null)}><div className="confirm-modal" role="dialog" aria-modal="true"><h3>Xóa ảnh sản phẩm?</h3><p>Ảnh sẽ được gỡ khỏi sản phẩm. Cleanup Cloudinary do backend kiểm soát.</p><div><button type="button" className="btn btn-light" disabled={busy} onClick={()=>setDeleting(null)}>Hủy</button><button type="button" className="btn btn-danger" disabled={busy} onClick={remove}>{busy?"Đang xóa...":"Xóa ảnh"}</button></div></div></div>}</section>}
