import { Banknote, LockKeyhole } from "lucide-react";
import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axiosClient from "../api/axiosClient";
import { useAuth } from "../contexts/AuthContext";
import { useCart } from "../contexts/CartContext";
import { formatCurrency } from "../utils/formatters";
export default function Checkout() {
  const { user } = useAuth(); const { items, total, clearCart } = useCart(); const navigate = useNavigate();
  const [address, setAddress] = useState({ fullName: user?.fullName || "", phone: user?.phone || "", province: "", district: "", ward: "", addressLine: "" }); const [voucherCode, setVoucherCode] = useState(""); const [voucher, setVoucher] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [orderId, setOrderId] = useState("");
  const change = (event) => setAddress({ ...address, [event.target.name]: event.target.value });
  const validateVoucher = async () => { setError(""); try { const { data } = await axiosClient.post("/vouchers/validate", { code: voucherCode, orderValue: total }, { sessionProtected: true }); setVoucher(data.data); } catch (requestError) { setVoucher(null); setError(requestError.response?.data?.message || "Không thể kiểm tra voucher."); } };
  const submit = async (event) => { event.preventDefault(); if (!items.length) return; setLoading(true); setError(""); try { const { data } = await axiosClient.post("/orders", { items: items.map((item) => ({ variantId: item.variantId, quantity: item.quantity })), shippingAddress: address, voucherCode: voucher?.code || "", paymentMethod: "COD" }, { sessionProtected: true }); setOrderId(data.data.order._id); clearCart(); } catch (requestError) { setError(requestError.response?.data?.message || "Không thể tạo đơn hàng."); } finally { setLoading(false); } };
  if (orderId) return <div className="container success-page"><span>✓</span><h1>Đặt hàng thành công</h1><p>Đơn hàng của bạn đã được ghi nhận.</p><button className="btn btn-dark" onClick={() => navigate(`/orders/${orderId}`)}>Xem đơn hàng</button></div>;
  if (!items.length) return <div className="container empty"><h2>Giỏ hàng đang trống</h2><Link to="/products">Tiếp tục mua sắm</Link></div>;
  return <div className="container checkout-page"><div className="page-intro compact"><span className="eyebrow">THANH TOÁN AN TOÀN</span><h1>Thanh toán COD</h1></div><form className="checkout-grid" onSubmit={submit}><section className="checkout-form"><h2>Thông tin nhận hàng</h2><div className="form-grid">{[["fullName","Họ và tên"],["phone","Số điện thoại"],["province","Tỉnh / thành"],["district","Quận / huyện"],["ward","Phường / xã"],["addressLine","Địa chỉ"]].map(([name,label]) => <label className={name === "addressLine" ? "wide" : ""} key={name}>{label}<input required name={name} value={address[name]} onChange={change} /></label>)}</div><h2>Phương thức thanh toán</h2><label className="payment-option active"><input type="radio" checked readOnly /><Banknote /><span><strong>Thanh toán khi nhận hàng (COD)</strong><small>VNPay sẽ được tích hợp ở phase riêng.</small></span></label></section><aside className="order-summary"><h2>Tóm tắt đơn hàng</h2>{items.map((item) => <div className="checkout-item" key={item.key}><img src={item.image} /><span>{item.productName}<small>{item.variantName} × {item.quantity}</small></span><strong>{formatCurrency(item.displayPrice * item.quantity)}</strong></div>)}<div><span>Tạm tính</span><strong>{formatCurrency(total)}</strong></div><label>Mã giảm giá</label><div className="voucher"><input value={voucherCode} onChange={(e) => { setVoucherCode(e.target.value); setVoucher(null); }} /><button type="button" onClick={validateVoucher}>Áp dụng</button></div>{voucher && <div><span>Giảm giá</span><strong>-{formatCurrency(voucher.discount)}</strong></div>}<div className="summary-total"><span>Tạm tính sau giảm</span><strong>{formatCurrency(voucher?.finalValue ?? total)}</strong></div>{error && <p className="form-error">{error}</p>}<button className="btn btn-dark full" disabled={loading}>{loading ? "Đang đặt hàng..." : "Đặt hàng"}</button><small><LockKeyhole /> Giá và tồn kho được backend xác nhận lại.</small></aside></form></div>;
}
