import { Check, ChevronRight, Minus, Plus, ShoppingBag, Star } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import axiosClient from "../api/axiosClient";
import { useAuth } from "../contexts/AuthContext";
import { useCart } from "../contexts/CartContext";
import { formatCurrency, formatDate } from "../utils/formatters";
import { normalizeProduct, variantDisplayPrice } from "../utils/productAdapter";
export default function ProductDetail() {
  const { id } = useParams(); const { user } = useAuth(); const { addToCart } = useCart();
  const [product, setProduct] = useState(null); const [variants, setVariants] = useState([]); const [variant, setVariant] = useState(null); const [image, setImage] = useState(0); const [qty, setQty] = useState(1); const [reviews, setReviews] = useState([]); const [reviewForm, setReviewForm] = useState({ rating: 5, comment: "" }); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [reviewError, setReviewError] = useState("");
  const loadProduct = useCallback(async () => { const { data } = await axiosClient.get(`/products/${id}`); const normalized = normalizeProduct(data.data.product, data.data.variants); setProduct(normalized); setVariants(data.data.variants); setVariant((current) => data.data.variants.find((item) => item._id === current?._id) || data.data.variants[0] || null); return normalized; }, [id]);
  const loadReviews = useCallback(async (productId) => { const { data } = await axiosClient.get(`/products/${productId}/reviews`); setReviews(data.data.reviews); }, []);
  useEffect(() => { setLoading(true); loadProduct().then((value) => loadReviews(value.id)).catch((requestError) => setError(requestError.response?.data?.message || "Không thể tải sản phẩm.")).finally(() => setLoading(false)); }, [loadProduct, loadReviews]);
  const submitReview = async (event) => { event.preventDefault(); setReviewError(""); try { await axiosClient.post(`/products/${product.id}/reviews`, { rating: Number(reviewForm.rating), comment: reviewForm.comment }, { sessionProtected: true }); setReviewForm({ rating: 5, comment: "" }); await Promise.all([loadProduct(), loadReviews(product.id)]); } catch (requestError) { setReviewError(requestError.response?.data?.message || "Không thể gửi đánh giá."); } };
  if (loading) return <div className="container empty"><p>Đang tải sản phẩm...</p></div>;
  if (error || !product) return <div className="container empty"><h2>Không thể hiển thị sản phẩm</h2><p>{error}</p><Link to="/products">Quay lại sản phẩm</Link></div>;
  const selectedPrice = variant ? variantDisplayPrice(variant) : product.salePrice;
  return <div className="container detail-page"><div className="breadcrumbs"><Link to="/">Trang chủ</Link><ChevronRight /><Link to="/products">Sản phẩm</Link><ChevronRight /><span>{product.name}</span></div>
    <div className="detail-grid"><div className="gallery"><div className="thumbs">{product.images.map((src, index) => <button className={index === image ? "active" : ""} key={src} onClick={() => setImage(index)}><img src={src} alt="" /></button>)}</div><div className="main-image"><img src={product.images[image] || "https://placehold.co/700x800?text=SKINORA"} alt={product.name} /></div></div>
      <div className="detail-info"><span className="brand">{product.brand}</span><h1>{product.name}</h1><div className="rating large"><Star fill="currentColor" /> {product.rating} <span>{product.reviewCount} đánh giá</span></div><p className="detail-description">{product.description}</p><div className="detail-price"><strong>{formatCurrency(selectedPrice)}</strong></div>
        <div className="variant-block"><div><strong>Phiên bản</strong><span>{variant ? (variant.stock > 0 ? `Còn ${variant.stock} sản phẩm` : "Hết hàng") : "Chưa có phiên bản khả dụng"}</span></div><div className="variant-row">{variants.map((item) => <button className={item._id === variant?._id ? "active" : ""} key={item._id} onClick={() => { setVariant(item); setQty(1); }}>{item.name || `${item.size} ${item.unit}`}<small>{formatCurrency(variantDisplayPrice(item))}</small></button>)}</div></div>
        <div className="purchase-row"><div className="qty"><button onClick={() => setQty(Math.max(1, qty - 1))}><Minus /></button><span>{qty}</span><button disabled={!variant || qty >= variant.stock} onClick={() => setQty(qty + 1)}><Plus /></button></div><button className="btn btn-dark grow" disabled={!variant || variant.stock <= 0} onClick={() => addToCart(product, variant, qty)}><ShoppingBag /> {variant?.stock > 0 ? "Thêm vào giỏ hàng" : "Hết hàng"}</button></div>
      </div></div>
    <div className="detail-sections"><article><span className="eyebrow">CÂU CHUYỆN SẢN PHẨM</span><h2>Công dụng</h2><p>{product.description || product.shortDescription}</p></article><article><h3>Thành phần nổi bật</h3><div className="tag-row">{product.ingredients.map((item) => <span key={item.normalizedName || item.name}>{item.name}</span>)}</div><h3>Hướng dẫn sử dụng</h3><p>{product.usage || "Đang cập nhật."}</p></article><article><h3>Phù hợp với</h3>{[...product.skinTypes, ...product.skinConcerns].map((item) => <p className="check-line" key={item}><Check /> {item}</p>)}<h3>Lưu ý</h3><p>{product.warnings.join(" · ") || "Đọc kỹ hướng dẫn trước khi sử dụng."}</p></article></div>
    <section className="reviews"><h2>Đánh giá từ khách hàng</h2><div className="review-summary"><strong>{product.rating}</strong><div><div className="stars">★★★★★</div><span>Dựa trên {product.reviewCount} đánh giá</span></div></div>
      {user ? <form onSubmit={submitReview}><div className="form-grid"><label>Điểm đánh giá<select value={reviewForm.rating} onChange={(e) => setReviewForm({ ...reviewForm, rating: e.target.value })}>{[5,4,3,2,1].map((value) => <option key={value} value={value}>{value} sao</option>)}</select></label><label>Bình luận<textarea value={reviewForm.comment} onChange={(e) => setReviewForm({ ...reviewForm, comment: e.target.value })} maxLength="2000" /></label></div>{reviewError && <p className="form-error">{reviewError}</p>}<button className="btn btn-dark">Gửi đánh giá</button></form> : <p><Link to="/login">Đăng nhập</Link> để viết đánh giá.</p>}
      <div className="order-cards">{reviews.length ? reviews.map((review) => <article key={review._id}><div><strong>{review.user?.fullName || "Khách hàng SKINORA"}</strong><span>{formatDate(review.createdAt)}</span></div><b>{"★".repeat(review.rating)}</b><p>{review.comment || "Không có bình luận."}</p></article>) : <div className="empty"><p>Chưa có đánh giá nào.</p></div>}</div>
    </section></div>;
}
